package rogeriogentil.data.structures.chapter03.reinforcement;

/**
 * Give the next five pseudorandom numbers generated by the process described on
 * page 113:
 *
 * next = (a ∗ cur + b) % n;
 *
 * , with a = 12, b = 5, and n = 100, and 92 as the seed for cur.
 *
 * @author Rogerio J. Gentil
 */
public class Exercise01 {

    public static void main(String[] args) {
        int seed = 92;

        PseudoRandom pseudoRandom = new PseudoRandom(seed);
        double first = pseudoRandom.next();
        double second = pseudoRandom.next();
        double third = pseudoRandom.next();
        double fourth = pseudoRandom.next();
        double fifth = pseudoRandom.next();

        System.out.println("1º: " + first);
        System.out.println("2º: " + second);
        System.out.println("3º: " + third);
        System.out.println("4º: " + fourth);
        System.out.println("5º: " + fifth);
    }

}
